import { Calendar } from '../types/calendar.model';

export const mockCalendars: Calendar[] = [
	{
		kind: 'calendar#calendarListEntry',
		id: 'garinmarion749@gmail.com',
		summary: 'Activités Marion',
		timeZone: 'Europe/Paris',
		colorId: '16',
		backgroundColor: '#00dcfb',
		foregroundColor: '#ffffff',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'jornetsimon@gmail.com',
		summary: 'Travail',
		location: 'SUPINFO, Place Michelet, 37000 Tours',
		timeZone: 'Europe/Paris',
		colorId: '16',
		backgroundColor: '#0a5eb5',
		foregroundColor: '#ffffff',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		notificationSettings: {
			notifications: [
				{
					type: 'eventResponse',
					method: 'email',
				},
			],
		},
		primary: true,
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'qv801uclagrrru0lqv46mdvrr8@group.calendar.google.com',
		summary: 'Activités',
		location: 'SUPINFO, Place Michelet, 37000 Tours',
		timeZone: 'Europe/Paris',
		colorId: '3',
		backgroundColor: '#b90e28',
		foregroundColor: '#ffffff',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: '656005f1g6d83rbjlr8b7qlsoc@group.calendar.google.com',
		summary: 'Autres',
		location: 'SUPINFO, Place Michelet, 37000 Tours',
		timeZone: 'Europe/Paris',
		colorId: '20',
		backgroundColor: '#cabdbf',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'addressbook#contacts@group.v.calendar.google.com',
		summary: 'Birthdays',
		description:
			'Displays birthdays, anniversaries, and other event dates of people in Google Contacts.',
		timeZone: 'Europe/Paris',
		summaryOverride: 'Contacts',
		colorId: '3',
		backgroundColor: '#ff4b0a',
		foregroundColor: '#ffffff',
		selected: true,
		accessRole: 'reader',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'm4cbuj3cb9sl9asfv8bpl6ug1s@group.calendar.google.com',
		summary: 'Evènements',
		location: 'SUPINFO, Place Michelet, 37000 Tours',
		timeZone: 'Europe/Paris',
		colorId: '13',
		backgroundColor: '#92e1c0',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'family02412757540959937483@group.calendar.google.com',
		summary: 'Family',
		timeZone: 'UTC',
		colorId: '17',
		backgroundColor: '#9a9cff',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'writer',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'e3nbf6vkdburr0148cnof2qcdk@group.calendar.google.com',
		summary: 'Moureuse et Moureux ♥️',
		timeZone: 'Europe/Paris',
		colorId: '2',
		backgroundColor: '#d06b64',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'pjo3csh3j5gcq2dbuijkafv1rs@group.calendar.google.com',
		summary: 'Radio',
		location: 'SUPINFO, Place Michelet, 37000 Tours',
		timeZone: 'Europe/Paris',
		colorId: '1',
		backgroundColor: '#711a76',
		foregroundColor: '#ffffff',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'boeqvbkc6cbc67f08n862q8j2c@group.calendar.google.com',
		summary: 'Releases',
		location: 'SUPINFO, Place Michelet, 37000 Tours',
		timeZone: 'Europe/Paris',
		colorId: '7',
		backgroundColor: '#2cc7ca',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'rpudapf65lgp495hlmkb38h9c4@group.calendar.google.com',
		summary: 'TV',
		location: 'SUPINFO, Place Michelet, 37000 Tours',
		timeZone: 'Europe/Paris',
		colorId: '8',
		backgroundColor: '#16a765',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'pve84361k2mfquap6c44tcf3d4@group.calendar.google.com',
		summary: 'Trajets',
		location: 'SUPINFO, Place Michelet, 37000 Tours',
		timeZone: 'Europe/Paris',
		colorId: '6',
		backgroundColor: '#e6c800',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: '2s84n3dd5fn7dgtm7pvr7u7luk@group.calendar.google.com',
		summary: 'Sport',
		location: 'SUPINFO, Place Michelet, 37000 Tours',
		timeZone: 'Europe/Paris',
		colorId: '18',
		backgroundColor: '#b99aff',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'dmb75glvtf10ve7uj23fvtl9kc@group.calendar.google.com',
		summary: 'Soirées',
		location: 'SUPINFO, Place Michelet, 37000 Tours',
		timeZone: 'Europe/Paris',
		colorId: '3',
		backgroundColor: '#f64f00',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: '00207pa8f8v1vnhlt0sdjb673k@group.calendar.google.com',
		summary: 'Repas',
		location: 'SUPINFO, Place Michelet, 37000 Tours',
		timeZone: 'Europe/Paris',
		colorId: '3',
		backgroundColor: '#882f00',
		foregroundColor: '#ffffff',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'nfl_33_%42altimore+%52avens#sports@group.v.calendar.google.com',
		summary: 'Baltimore Ravens',
		timeZone: 'Europe/Paris',
		summaryOverride: 'Baltimore Ravens',
		colorId: '20',
		backgroundColor: '#cabdbf',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'reader',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'fr.french#holiday@group.v.calendar.google.com',
		summary: 'Jours fériés en France',
		description: 'Jours fériés et fêtes légales en France',
		timeZone: 'Europe/Paris',
		summaryOverride: 'Jours fériés',
		colorId: '11',
		backgroundColor: '#fbe983',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'reader',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'pss5i6fogvve57vj92j4b9pqm0@group.calendar.google.com',
		summary: 'Todoist',
		timeZone: 'Europe/Paris',
		colorId: '12',
		backgroundColor: '#fad165',
		foregroundColor: '#000000',
		selected: true,
		accessRole: 'owner',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
	{
		kind: 'calendar#calendarListEntry',
		id: 'simon.jornet@y42.com',
		summary: 'Work',
		timeZone: 'Europe/Berlin',
		summaryOverride: 'y42',
		colorId: '16',
		backgroundColor: '#35359e',
		foregroundColor: '#ffffff',
		selected: true,
		accessRole: 'reader',
		defaultReminders: [],
		conferenceProperties: {
			allowedConferenceSolutionTypes: ['hangoutsMeet'],
		},
	},
];
